input {
    tcp {
        port => 5022
        codec => json_lines
    }
}

output {
    if [application] == "audio-messages-backend" {
        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            index => "audio-messages-logs-%{+YYYY.MM.dd}"
            user => "${ELASTIC_USERNAME}"
            password => "${ELASTIC_PASSWORD}"
        }
    } else if [application] == "sender-api" {
        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            index => "sender-api-logs-%{+YYYY.MM.dd}"
            user => "${ELASTIC_USERNAME}"
            password => "${ELASTIC_PASSWORD}"
        }
    } else if [application] == "text-to-voice" {
        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            index => "text-to-voice-logs-%{+YYYY.MM.dd}"
            user => "${ELASTIC_USERNAME}"
            password => "${ELASTIC_PASSWORD}"
        }
    }
    stdout {
        codec => rubydebug
    }
}